POST http://localhost:3000/api/admin/category
Content-Type: application/json

{
    "isSubCategory": false,
    "categoryId": "",
    "data": {
        "title": "Category 4",
        "description": "Category 4 description",
        "productIds": [
            "642be58182f721bfc420466c",
            "642be58382f721bfc420466e",
            "642be58b82f721bfc4204670",
            "642be58d82f721bfc4204672"
        ]
    }
}

###

POST http://localhost:3000/api/admin/category
Content-Type: application/json

{
    "isSubCategory": true,
    "categoryId": "642be6d582f721bfc4204680",
    "data": {
        "title": "Sub Category 4 for category 4",
        "description": "Sub Category 4 for category 4 description",
        "productIds": [
            "642be58182f721bfc420466c"
        ]
    }
}

###

GET http://localhost:3000/api/admin/category/

###

GET http://localhost:3000/api/admin/category/642be6a982f721bfc4204674/642be6b582f721bfc4204677

###

GET http://localhost:3000/api/admin/category/642baf66265084143672dec3/642baf68265084143672dec8

###

PUT http://localhost:3000/api/admin/category/642bb79e8eadb0e7dc74f8f3
Content-Type: application/json

{
    "isSubcategory": false,
    "newData": {
        "title": "Category 2",
        "description": "Category 2 description",
        "subCategoryIds": [],
        "productIds": [
            "642bb7608eadb0e7dc74f8e9",
            "642bb7638eadb0e7dc74f8eb",
            "642bb7688eadb0e7dc74f8ef"
        ]
    }
}

###

PUT http://localhost:3000/api/admin/category/642baf68265084143672dec8
Content-Type: application/json

{
    "isSubCategory": true,
    "newData": {
        "title": "Sub Category 2 updated",
        "description": "Sub Category 2 description updated",
        "productIds": [
            "642ba214265084143672deae"
        ]
    }
}

###

DELETE http://localhost:3000/api/admin/category/642be6c582f721bfc420467b/642be6d582f721bfc4204680/642be73c82f721bfc4204691