GET http://localhost:3000/api/public/common/top-popular-articles

###

POST http://localhost:3000/api/public/common/add-to-cart
Content-Type: application/json

{
    "productId": "",
    "quantity": 1,
    "options": [
        {
            "optionId": "",
            "title": "",
            "value": ""
        },
        {
            "optionId": "",
            "title": "",
            "value": ""
        }
    ]
}