### 

POST http://localhost:3000/api/public/user/register
Content-Type: application/json

{
    "email": "test.6@gmail.com",
    "password": "tester"
}

### verify registration email via token

GET http://localhost:3000/api/public/user/register/verify
?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QuNEBnbWFpbC5jb20iLCJpYXQiOjE2ODA4NTI4MTIsImV4cCI6MTY4MDg1MzExMn0.htNlyXCDU_dkni-UFvDJiDOp_NH03lZN4h5mAz1vgCE

### login

POST http://localhost:3000/api/public/user/login
Content-Type: application/json

{
    "email": "test.5@gmail.com",
    "password": "tester"
}

### get user profile

GET http://localhost:3000/api/public/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmY2FiYTk5MzI4ZWQ0MTljZDQ3MGUiLCJpYXQiOjE2ODA4NjQ4NzUsImV4cCI6MTY4MDg2NjMxNX0.VyGiP4OBRrdtFfxE4yG3rrmoh7bINsPw8CRhyM2fbgg