### 

POST http://localhost:3000/api/public/user/register
Content-Type: application/json

{
    "email": "test.9@gmail.com",
    "password": "tester"
}

### verify registration email via token

GET http://localhost:3000/api/public/user/register/verify
?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QuNEBnbWFpbC5jb20iLCJpYXQiOjE2ODA4NTI4MTIsImV4cCI6MTY4MDg1MzExMn0.htNlyXCDU_dkni-UFvDJiDOp_NH03lZN4h5mAz1vgCE

### login

POST http://localhost:3000/api/public/user/login
Content-Type: application/json

{
    "email": "test.5@gmail.com",
    "password": "tester1"
}

### get user profile

GET http://localhost:3000/api/public/user/

### refresh token

GET http://localhost:3000/api/public/user/refresh

### edit profile info

PUT http://localhost:3000/api/public/user/profile-info
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "five",
    "contactNumber": "1234567890"
}

### edit shipping info

PUT http://localhost:3000/api/public/user/shipping-info
Content-Type: application/json

{
    "name": "",
    "contactNumber": "",
    "address": "test address",
    "city": "test city",
    "state": "test state",
    "country": "test country",
    "postalCode": "123456"
}

### change password

PUT http://localhost:3000/api/public/user/change-password
Content-Type: application/json

{
    "password": "tester",
    "newPassword": "tester1"
}