POST http://localhost:3000/api/admin/blog/
Content-Type: application/json

{
    "heading": {
        "title": "Heading Title 2",
        "description": "Heading Description 2",
        "author": "Heading Author 2"
    },
    "sections": [
        {
            "title": "Section Title 1 o 2",
            "description": "Section Description with minimal rich text formatting.<br>Sample list: <ul><li>Item 1</li><li>Item 2</li></ul>"
        },
        {
            "title": "Section Title 2 o 2",
            "description": "Section Description 2"
        }
    ],
    "type": "normal",
    "tags": ["tag1", "tag4"]
}

###

GET http://localhost:3000/api/admin/blog/

###

PUT http://localhost:3000/api/admin/blog/642cf0857d35085b95e6f6b8
Content-Type: application/json

{
    "heading": {
        "title": "Heading Title - Updated",
        "description": "Heading Description",
        "author": "Heading Author"
    },
    "sections": [
        {
            "title": "Section Title",
            "description": "Section Description"
        },
        {
            "title": "Section Title",
            "description": "Section Description"
        }
    ],
    "type": "normal",
    "tags": ["tag1", "tag2"]
}

###

DELETE http://localhost:3000/api/admin/blog/642cf0857d35085b95e6f6b8

###