POST http://localhost:3000/api/admin/cart/Russel.Klocko75@yahoo.com
Content-Type: application/json

{
    "productId": "642cbbec19721b73bb77eb81",
    "quantity": 6,
    "options": [       
        {
            "optionId": "603b7bb82b6d442e6e0c1e57",
            "title": "Color",
            "value": "Red"
        },
        {
            "optionId": "603b7bb82b6d442e6e0c1e58",
            "title": "Size",
            "value": "XL"
        }
    ]
}

###

GET http://localhost:3000/api/admin/cart/Russel.Klocko75@yahoo.com

###

PUT http://localhost:3000/api/admin/cart/Russel.Klocko75@yahoo.com
Content-Type: application/json

{
    "productId": "642cbbec19721b73bb77eb7f",
    "quantity": 0,
    "options": [
        {
            "optionId": "603b7bb82b6d442e6e0c1e57",
            "title": "Color",
            "value": "Red"
        },
        {
            "optionId": "603b7bb82b6d442e6e0c1e58",
            "title": "Size",
            "value": "XL"
        }
    ]
}

###

DELETE http://localhost:3000/api/admin/cart/delete?email=Russel.Klocko75@yahoo.com&productIds=642cbbec19721b73bb77eb7f,642cbbec19721b73bb77eb81
