POST http://localhost:3000/api/admin/category
Content-Type: application/json

{
    "isSubCategory": false,
    "categoryId": "",
    "data": {
        "title": "Category 1",
        "description": "Category 1 description",
        "productIds": [
            "642cbbec19721b73bb77eb7e",
            "642cbbec19721b73bb77eb7f",
            "642cbbec19721b73bb77eb86",
            "642cbbec19721b73bb77eb81",
            "642cbbec19721b73bb77eb82",
            "642cbbec19721b73bb77eb83"
        ]
    }
}

###

POST http://localhost:3000/api/admin/category
Content-Type: application/json

{
    "isSubCategory": true,
    "categoryId": "642d22a17d35085b95e6f6c9",
    "data": {
        "title": "Sub Category 1 for category 1",
        "description": "Sub Category 3 for category 1 description",
        "productIds": [
            "642cbbec19721b73bb77eb81",
            "642cbbec19721b73bb77eb82",
            "642cbbec19721b73bb77eb83"
        ]
    }
}

###

GET http://localhost:3000/api/admin/category/

###

GET http://localhost:3000/api/admin/category/642be6a982f721bfc4204674/642be6b582f721bfc4204677

###

GET http://localhost:3000/api/admin/category/642baf66265084143672dec3/642baf68265084143672dec8

###

PUT http://localhost:3000/api/admin/category/642bb79e8eadb0e7dc74f8f3
Content-Type: application/json

{
    "isSubcategory": false,
    "newData": {
        "title": "Category 2",
        "description": "Category 2 description",
        "subCategoryIds": [],
        "productIds": [
            "642bb7608eadb0e7dc74f8e9",
            "642bb7638eadb0e7dc74f8eb",
            "642bb7688eadb0e7dc74f8ef"
        ]
    }
}

###

PUT http://localhost:3000/api/admin/category/642baf68265084143672dec8
Content-Type: application/json

{
    "isSubCategory": true,
    "newData": {
        "title": "Sub Category 2 updated",
        "description": "Sub Category 2 description updated",
        "productIds": [
            "642ba214265084143672deae"
        ]
    }
}

###

DELETE http://localhost:3000/api/admin/category/642d22a17d35085b95e6f6c9