POST http://localhost:3000/api/admin/products/642e546175e308139831ad1a/options/
Content-Type: application/json

{
    "title": "option 2",
    "values": ["value 1", "value 2"]
}

###

GET http://localhost:3000/api/admin/products/642a82cd8326e5f3242c11df/options

###

GET http://localhost:3000/api/admin/products/642a82cd8326e5f3242c11df/options/642a9e96fc97d1aa5c77d92b/642b6af9fe1df411cb4faad9

###

PUT http://localhost:3000/api/admin/products/642a82cd8326e5f3242c11df/options
Content-Type: application/json

{
    "optionId": "642aa901fc97d1aa5c77d939",
    "newOption": {
        "title": "option 3",
        "values": ["value 101", "value 202"]
    }
}

###

DELETE http://localhost:3000/api/admin/products/642a82cd8326e5f3242c11df/options/642a9e96fc97d1aa5c77d92b