POST http://localhost:3000/api/admin/products
Content-Type: application/json

{
    "title": "Product test 21",
	"price": 200,
	"salePrice": 250,
	"stock": 2250,
	"description": "A product description with rich text formatting. <br>Sample list: <ul><li>Item 1</li><li>Item 2</li></ul>"
}

###

GET http://localhost:3000/api/admin/products/

###

GET http://localhost:3000/api/admin/products/642cbbec19721b73bb77eb7e

###

PUT http://localhost:3000/api/admin/products/642a82cd8326e5f3242c11df
Content-Type: application/json

{
	"title": "Product test one updated"
}

###

DELETE http://localhost:3000/api/admin/products/delete/642a82cd8326e5f3242c11df/
